apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynatrace_service_account
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dynatrace
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: dynatrace-service-account
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
