apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynakube
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dynatrace
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: dynakube/overlay/my-cluster
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
